version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  fastapi-app:
    image: "amina444/venv-fastapi-app:latest"
    container_name: "fastapi_app"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge 
